FROM node:22-alpine

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm ci

# Copy the rest of the codebase
COPY . .

# Set necessary environment variables
ENV NODE_ENV=test

# Expose API port
EXPOSE 8081

# Keep container running for tests
CMD ["npm", "run", "test:api:docker"]