version: '3.8'

services:
  postgres-test:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: arbi_test
    ports:
      - "5433:5433"
    command: -p 5433
    volumes:
      - postgres-test-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -p 5433" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-test-data:
