version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - NODE_ENV=test
      - RUNNING_IN_DOCKER=true
      - TEST_DB_HOST=postgres-test
      - TEST_DB_PORT=5433
      - TEST_DB_USERNAME=postgres
      - TEST_DB_PASSWORD=postgres
      - TEST_DB_NAME=arbi_test
    ports:
      - "8081:8081"
    depends_on:
      postgres-test:
        condition: service_healthy
    command: [ "npm", "run", "test:api:docker" ]
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    networks:
      - arbi-test-network

  # Reference existing postgres-test container rather than creating a new one
  postgres-test:
    extends:
      file: docker-compose.test.yml
      service: postgres-test
    networks:
      - arbi-test-network

volumes:
  node_modules:


networks:
  arbi-test-network:
    name: arbi-service_default
    external: true
